apiVersion: apps/v1
kind: Deployment
metadata:
  name: levi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: levi-api
  template:
    metadata:
      labels:
        app: levi-api
    spec:
      containers:
        - name: levi-api
          image: us-docker.pkg.dev/unstable-unicorns-389016/levi-api          
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10